management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    beans:
      enabled: false
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: /ind-arac?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong&nullCatalogMeansCurrent=true
    username: root
    password:
  activiti:
    history-level: full
    check-process-definitions: false
    database-schema-update: true
server:
  context-path: "/workflow"
  port: 8081
tenantInit:
  poolMaximumActiveConnections: 300
#  mybatis相对位置指定
mybatis:
  mapper-locations: classpath:/mapper/*.xml